services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "8080:80"
